### ISSUE TITLE
vxtwitter embeds don't work on all mobile devices

### ISSUE THREAD

**Issue by solitarius88** [dylanpdx/BetterTwitFix#10]
When using vxtwitter in the discord app on my 2 Android phones, embeds don't work, when I hit the play button on the video, it still opens in the external web browser. 

But I've asked some other people and for them it works properly, as it plays the video from the tweet straight in their discord app on their phones, be it on Android or iphone.

Any idea why is this happening and is there anything I can do to make it work as intended on my phones?

**Comment by dylanpdx** [comment]
I don't think this is an issue on my end, and it depends on the version of Discord the user has? I think some beta versions of Discord are inlining videos within the app but I'm not entirely sure

**Comment by dylanpdx** [comment]
Gonna go ahead and close this as this was most likely a thing with the new Discord redesign
