### ISSUE TITLE
Site certificate broken or incomplete since 24-06-2023

### ISSUE THREAD

**Issue by Dwarden** [dylanpdx/BetterTwitFix#102]
https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&s=44.214.7.93#whyNotTrusted
https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&s=18.207.38.70#whyNotTrusted

browsers will now consider the https://vxtwitter.com as insecure / non trust-able domain

as result there is also lack of `Strict-Transport-Security`

and some other issues (headers etc.) most likely due to the same issue with certificate

**Comment by dylanpdx** [comment]
Hi, I changed the hosting setup & certificates earlier and the IP addresses listed in those reports are outdated

https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&latest

https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&s=172.67.70.184&latest
https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&s=104.26.0.84&latest
https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&s=104.26.1.84&latest

No issues for me on accessing it from browsers or performing requests from various servers I own, although I might be wrong so please keep me updated on if you managed to get it working

**Comment by Dwarden** [comment]
thanks, it seems slightly better now (B)
https://www.ssllabs.com/ssltest/analyze.html?d=vxtwitter.com&hideResults=on&latest

still not as good as compared to e.g. fxtwitter  (A+)
https://www.ssllabs.com/ssltest/analyze.html?d=fxtwitter.com&hideResults=on&latest

about the other errors (headers) i will take look later when i can do different check type ...

**Comment by Dwarden** [comment]
1. Header "Strict-Transport-Security" is missing (not set)
 ( HTTP-Strict-Transport-Security (HSTS) header forces browsers to access the website via HTTPS )

2. Header "access-control-allow-origin" isn't properly configured. 
 returns 'Access-Control-Allow-Origin: null' for request `Origin: null`

**Comment by dylanpdx** [comment]
1. A redirect is configured, even without that header, all clients are forced to redirect to the https version of the website
2. The `access-control-allow-origin` header is always set to the same value as the `Origin` header. Sending a request with `Origin: abc123` would return `access-control-allow-origin header: abc123`. This is intended behavior of flask-cors and is documented here: https://flask-cors.corydolphin.com/en/latest/configuration.html#cors-origins-setting
