### ISSUE TITLE
Add prepend-only support?

### ISSUE THREAD

**Issue by likuilin** [dylanpdx/BetterTwitFix#107]
Hi! I use IFTTT in order to post tweets to a Discord channel via a webhook.

My issue is, IFTTT doesn't allow arbitrary rewriting of parameters without Pro+. The link to the tweet is provided as a parameter called `{{LinkToTweet}}` whose value is `"https://twitter.com/Twitter/status/1492120137205526528"` in its entirety. Because of this, there's no way to replace twitter with vxtwitter without a JS filter, which requires the highest subscription tier of IFTTT.

However, another option would be to prepend it like so: `https://vxtwitter.com/{{LinkToTweet}}` which would expand to `"https://vxtwitter.com/https://twitter.com/Twitter/status/1492120137205526528"`. This currently generates a link that has a correct-looking embed, but clicking the link sends you to a redirect loop that eventually 400s. The redirects go:

* https://vxtwitter.com/https://twitter.com/Twitter/status/1492120137205526528
* 301 to https://vxtwitter.com/twitter.com/Twitter/status/1492120137205526528
* 301 to https://vxtwitter.com/twitter.com/Twitter/status/twitter.com/Twitter/status/1492120137205526528
* 301 to https://vxtwitter.com/twitter.com/Twitter/status/twitter.com/Twitter/status/twitter.com/Twitter/status/twitter.com/Twitter/status/1492120137205526528

...and so on. Can the nginx config be changed, please, to support this use case?

**Comment by dylanpdx** [comment]
I'll look into fixing this, thank you for bringing it to my attention!

**Comment by dylanpdx** [comment]
This should be fixed now, it was tricky! Please make sure it's working and close the issue if so!

**Comment by likuilin** [comment]
It looks like `https://vxtwitter.com/https://twitter.com/Twitter/status/1492120137205526528` now directly 301s to `https://twitter.com/Twitter/status/1492120137205526528` which means the former link doesn't make an embed
