### ISSUE TITLE
rendercombined add unnecessary borders to the third image when combining two portrait and one landscape images

### ISSUE THREAD

**Issue by fireattack** [dylanpdx/BetterTwitFix#109]
When combining three pictures, vxtwitter uses 

```
+---+---+
| A | B |
+---+---+
|   C   |
+---+---+

```
arrangement. This is totally fine, and when image C is portrait it would fit-to-height just fine, but when it is landscape sometimes for some reason it isn't set as fit-to-window.

Example: https://convert.vxtwitter.com/rendercombined.jpg?imgs=https://pbs.twimg.com/media/F0BJpCgakAIxIUf.jpg,https://pbs.twimg.com/media/F0BJpCeaYAA-n9y.jpg,https://pbs.twimg.com/media/F0BJpCfaEAEB8mz.jpg

![image](https://github.com/dylanpdx/BetterTwitFix/assets/4130991/d991b813-fa38-4236-a01f-984dad806254)

**Comment by dylanpdx** [comment]
Thank you for providing an example, I'll look into this!

**Comment by dylanpdx** [comment]
This should be rendering correctly now

**Comment by Nama** [comment]
@dylanpdx this is still broken with 4 images (not sure, but another case was broken, too. will report if i see).
should i open a new issue?
https://vxtwitter.com/datcravat/status/1679584240499847169
![image](https://github.com/dylanpdx/BetterTwitFix/assets/2297270/b42a40f3-5207-4629-83e8-64ae7125c1ab)

**Comment by dylanpdx** [comment]
@Nama This seems to be only 3 images? I do admit it looks a little strange though, I'm guessing the unusual sizes of the first and second images is causing a lot of empty space in the layout
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/0604f869-aae6-4264-9a32-c4f30e16f30b)
Kind of a tricky situation based on how I'm combining images, but it could probably be compacted into something like this
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/3a14b62e-a641-4f5a-b9db-7d521d2a9dfa)

Anyways, I think this is a separate issue so feel free to open a new one and we can continue discussion there

**Comment by Nama** [comment]
> This seems to be only 3 images?

me dumb, opened #118
