### ISSUE TITLE
Show multiple images without c.vx?

### ISSUE THREAD

**Issue by ZornTaov** [dylanpdx/BetterTwitFix#11]
I habitually share stuff from twitter to various groups in telegram, and it's always a hassle when the tweet has multiple images in it.  Recently Telegram has gotten super unreliant in embedding Twitter posts (either shows the post, shows just the text "[Twitter in some language] / Twitter", or fails to embed entirely) so I've had to use vx if there's a single image or c.vx if there's multiple.  The problem is Telegram likes to lower the quality of images, even embedded ones, so the combined image gets shrunken down to the point where if there's text (like in a comic) you can't read any of it.

So my request is: Please find a way to show all images as separate image embeds in the same link?  Discord will sometimes support it (mostly on desktop I think?) and Telegram used to support it as well, so it's definitely possible somehow.

**Comment by dylanpdx** [comment]
It's not supported for general websites, at least not for Discord. Only bots and "authorized" websites are able to make those fancy embeds. While it's not documented anywhere, I found this issue in their API documentation that was marked by a developer as "documentation needed" https://github.com/discord/discord-api-docs/issues/1593, specifically:
> some providers such as twitch and youtube get special embeds which cannot be simulated by other third-party providers

For Telegram I will have to check on how their embeds work but it's probably a similar situation.

You mentioned the quality being bad, which is partly my fault as I do crunch the images down a bit to save on loading time for the end user. I'll see if I can improve that, so I'll leave this open.

**Comment by dylanpdx** [comment]
Made a change that should hopefully embed at higher quality. Let me know if it works

**Comment by ZornTaov** [comment]
Definitely looks better so far 👍

**Comment by dylanpdx** [comment]
Yeah, unfortunately Telegram embeds don't support more than 1 image per embed on third party websites.
I've improved the quality of the combined embeds as much as I can but I don't think there's much else I can do for now
