### ISSUE TITLE
how to install for dummies

### ISSUE THREAD

**Issue by robesasu** [dylanpdx/BetterTwitFix#113]
Not an issue, but but could you please provide the steps so someone like me, who has no linux knowledge, can deploy your bot on an ubuntu droplet?

Much appreciated if possible!

**Comment by dylanpdx** [comment]
Hey, I forgot to follow up on this- I added some instructions on how to set it up in three different configurations, it should be under the readme. The simplest way is using Docker, but setting it up directly with python, and using the serverless framework are also available.

Please let me know if any clarification or improvements are needed

**Comment by robesasu** [comment]
super, thanks!
