### ISSUE TITLE
OG tweet is embedded instead of comment

### ISSUE THREAD

**Issue by Nama** [dylanpdx/BetterTwitFix#119]
All the examples I could fined are NSFW tagged by twitter. Maybe thats related?
This two links have the same output:
https://vxtwitter.com/EchoSaber1/status/1679566086549786625
https://vxtwitter.com/EchoSaber1/status/1679566088181370881

**Comment by dylanpdx** [comment]
This should be fixed in a bit, it might take a while for Discord's (or other messaging platforms) to update their cache
