### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by graphicjazz** [dylanpdx/BetterTwitFix#126]
Any plans to set something up for nicovideo.jp?

**Comment by dylanpdx** [comment]
Not sure, it depends on how many people would use it and what the issues with it are

**Comment by graphicjazz** [comment]
I see, guessing it's not a popular request judging by your response. Well if you ever feel like looking into it and need data I'll be happy to provide.

**Comment by dylanpdx** [comment]
First time I've been asked for nicovideo, but if there's enough demand I suppose I could whip something up
