### ISSUE TITLE
Text cutting off

### ISSUE THREAD

**Issue by 0xallie** [dylanpdx/BetterTwitFix#128]
https://vxtwitter.com/rockstargames/status/1689969964923432960

The text cuts off after "Today, we are proud to announce that".

![Screenshot of the problematic embed on Discord](https://github.com/dylanpdx/BetterTwitFix/assets/482367/aa6fb234-3681-4f00-a4a3-f4dc40a04c8a)

**Comment by dylanpdx** [comment]
Should be fixed now
