### ISSUE TITLE
Twitter links are now “X.com/username” 

### ISSUE THREAD

**Issue by kevosmin** [dylanpdx/BetterTwitFix#129]
So since Twitter changed to X, their links to posts also changed 
![IMG_0047](https://github.com/dylanpdx/BetterTwitFix/assets/36827792/5d9e2d54-7a3d-459c-9920-81f5898c885a)

**Comment by Nama** [comment]
x.com still redirects to twitter.com. and it might even take longer to change the API URLs.
So, nothing changed yet and everything of vxtwitter still works.

**Comment by dylanpdx** [comment]
Oh my god are you serious

Bleh, I'll have to work something out

**Comment by dylanpdx** [comment]
You should be able to use [fixvx.com](http://fixvx.com) with those new links (add fixv right before the x)
Working on additional names that could be used as well

**Comment by alsotang** [comment]
nodejs example

```js
const twitterUrl = 'https://x.com/dotey/status/1706062780955074614?s=20'
const twitterUrlObj = new URL(twitterUrl)
twitterUrlObj.host = 'c.vxtwitter.com'
twitterUrlObj.toString()
```
