### ISSUE TITLE
Twitter Embed Fail (2023-08-14)

### ISSUE THREAD

**Issue by TomoSuperFan** [dylanpdx/BetterTwitFix#132]
So apparently, some links are failing to embed, with them saying Unknown Error. I don't know what's going on.

**Comment by dylanpdx** [comment]
Seems to be the same issue as #130, Twitter keeps changing things on their end which is breaking embeds.
Will look into it ASAP

**Comment by TomoSuperFan** [comment]
Thanks. I hope this is resolved because some vxtweets are working, while others aren't.

**Comment by dylanpdx** [comment]
Should be fixed now
