### ISSUE TITLE
Add t.co shortened link replacement with real links

### ISSUE THREAD

**Issue by iGerman00** [dylanpdx/BetterTwitFix#134]
FxTwitter has it, [seems easy to implement](https://github.com/FixTweet/FixTweet/blob/main/src/helpers/linkFixer.ts)

**Comment by dylanpdx** [comment]
This is already implemented
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/6eb0319a-d328-4358-8d78-ae802dfc1906)

**Comment by iGerman00** [comment]
My bad
