### ISSUE TITLE
Fix embedding Twitter links in Mastodon posts?

### ISSUE THREAD

**Issue by ViaRationis** [dylanpdx/BetterTwitFix#138]
If this can be within the scope of this project... It's currently hit-or-miss whether a Twitter link will embed a preview correctly when sharing on Mastodon. And I presume other sites as well. I'm hoping the fediverse gains more traction, and if vxTwitter can be used the same way as on Discord, it could improve our ability to share.

**Comment by dylanpdx** [comment]
I'm not sure how Mastodon currently fetches information about links, but it should be simple to add support. I'll look into it and get back to you in a bit

**Comment by dylanpdx** [comment]
I've just allowed Mastodon's link grabber to access vxTwitter, but it seems like they only display very little information about the post. This was tested with a text post but maybe image posts will display the image itself, I haven't checked
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/a5d0c71e-9281-4f4d-9ec9-7569a38c2da2)
