### ISSUE TITLE
Clickable links within embed

### ISSUE THREAD

**Issue by Wazhai** [dylanpdx/BetterTwitFix#140]
Would it be possible to make URLs clickable? 

Currently the only way to open links from vxtwitter embeds is to copy that part of the text manually. This is ever less convenient on mobile because only the entire tweet text can be copied through click-and-hold. Blue-underlined URLs would be a great addition

**Comment by dylanpdx** [comment]
Don't think this is possible with the restrictions Discord embeds have. Only 'official' websites (Twitter, youtube, etc) can have those features on their embeds
