### ISSUE TITLE
How to use it with x.com?

### ISSUE THREAD

**Issue by minatahatsune** [dylanpdx/BetterTwitFix#142]
Since Twitter is changing its domain to x.com, how can I use this tool with x,com?

**Comment by Nama** [comment]
[fixvx.com](http://fixvx.com/) via #129

**Comment by dylanpdx** [comment]
Replace x.com links with fixvx.com (add fixv at the beginning)

**Comment by minatahatsune** [comment]
thank you, I will close this.

**Comment by minatahatsune** [comment]
thank you, I will close this.
