### ISSUE TITLE
vxTwitter doesn't work with X links

### ISSUE THREAD

**Issue by XangelMusic** [dylanpdx/BetterTwitFix#143]
So recently Twitter/X updated how you share on mobile, replacing Twitter links with X links instead, e.g. https://x.com/sorainu1211EAKA/status/1702276756944851399

vxTwitter doesn't seem to work with X links at this moment.

EDIT: I should elaborate. You can change X to vxtwitter and it will work, but it is quite a hassle to do so in my opinion.

**Comment by dylanpdx** [comment]
Duplicate of #142 
tl;dr Replace x.com links with fixvx.com (add fixv at the beginning)
