### ISSUE TITLE
"GIFs" don't work anymore

### ISSUE THREAD

**Issue by Nama** [dylanpdx/BetterTwitFix#15]
I'm sure "GIFs" used to work before, but now I always get an error. Videos and images still work.

Example Link: https://vxtwitter.com/pixeljess/status/1569713891336126464
![image](https://user-images.githubusercontent.com/2297270/190026587-443e1897-bc7f-4691-9698-9b85817a9243.png)

I hope this is easy fixable. Thank you for BetterTwitFix!

**Comment by dylanpdx** [comment]
Hi! This issue should be fixed now!
For some reason, twitter wasn't giving me the correct video info for certain tweets, but I've implemented a quick fix for it.
Feel free to re-open this issue if it happens again 👍
