### ISSUE TITLE
Twitter escaped HTML chars in API text

### ISSUE THREAD

**Issue by Scrxtchy** [dylanpdx/BetterTwitFix#152]
twitter would convert some chars like `&` `>` and `<` to their HTML-safe counterparts in tweet text as a security measure on itself or third party sites. Tweets that are embeded from the VNF data on BTF don't have this issue, but when fetched over the BTF API, then this issue starts to appear
https://github.com/dylanpdx/BetterTwitFix/blob/main/twitfix.py#L226

from the tweetdeck source, if it's easier to process these in code rather than fetching the expected text from the server
```js
        var HTML_ENTITIES = {
            '&': '&amp;',
            '>': '&gt;',
            '<': '&lt;',
            '"': '&quot;',
            '\'': '&#39;'
        };
```

**Comment by dylanpdx** [comment]
This should be fixed now!
