### ISSUE TITLE
Show Community Note

### ISSUE THREAD

**Issue by NilsEnevoldsen** [dylanpdx/BetterTwitFix#168]
If a post has a visible Community Note, it would be nice to show the contents of that note, or the abbreviated contents, or even that a Community Note exists. I don't have a specific UX in mind.

**Comment by dylanpdx** [comment]
The space I have on embeds is quite limited so I'd probably have to add an emoji (or text that says "this post has a community note"

**Comment by NilsEnevoldsen** [comment]
Some possibilities:

Emoji indicating warning or caution: ⚠️🚫

Emoji indicating investigation or justice: ⚖️👮🕵️‍♂️

Emoji indicating noting or tagging: 🗒️📝📋🏷️

I think ⚠️ might be a good one. Perhaps `⚠️ Note`, `⚠️ Noted`, or `⚠️ Community Note` if those fit?

**Comment by dylanpdx** [comment]
Here are a couple of concepts I played around with (Not implemented, just mockups)

In the top "Website name" field
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/98542b56-0d47-49be-8e03-80164a469566)

Along with username
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/49c9fae7-2c70-409f-8ff9-474456eaf55f)

Under likes
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/acaaf1c3-f58a-488b-abba-984c1c4492c7)

Under likes with full note
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/349cf14c-20be-46e5-a424-4dc633df3353)

I'm gravitating towards adding the first one, and the last two would cause issues for super long tweets.

Additionally, while complicated, I could add it so adding ?note or /note to the URL will show the note text
