### ISSUE TITLE
Tweet User Profile Picture

### ISSUE THREAD

**Issue by Shak-codes** [dylanpdx/BetterTwitFix#170]
Is there any way we could include the ability to get the URL of the profile picture of the user that made the tweet?

**Comment by dylanpdx** [comment]
If you mean through the API, then I can most likely ass a field with a URL of the user's profile picture

**Comment by Shak-codes** [comment]
> If you mean through the API, then I can most likely ass a field with a URL of the user's profile picture

That would be perfect, thank you so much

**Comment by dylanpdx** [comment]
This should be implemented now. Please close if it works for you!
