### ISSUE TITLE
API - Internal Server Error

### ISSUE THREAD

**Issue by Aaeeschylus** [dylanpdx/BetterTwitFix#179]
At some point in the last 12 hours, the API has stopped functioning. Even the example in the readme no longer works (https://api.vxtwitter.com/Twitter/status/1577730467436138524)

When doing any call to the API, the result is: 

Internal Server Error
{"message": "Failed to extract tweet (Processing error)"}

**Comment by mysterypaint** [comment]
Hello! I am also experiencing the same with another URL: [](https://api.vxtwitter.com/kikkuk222/status/1735825087511847111)

Hoping this can be resolved in due time; Thank you for the amazing Twitter workaround!

**Comment by dylanpdx** [comment]
Currently investigating the cause, thanks for letting me know!

**Comment by dylanpdx** [comment]
API should be slowly recovering now. Twitter broke one of their endpoints and caused some issues down the line for me

**Comment by dylanpdx** [comment]
This should be fixed now, sorry that it took so long!

**Comment by 8times4** [comment]
> This should be fixed now, sorry that it took so long!

Hmm, just fyi but seems to be broken again?

**Comment by dylanpdx** [comment]
Not seeing any issues on my end, is there a specific tweet causing it?

**Comment by Aaeeschylus** [comment]
It has been working perfectly fine for me since you said it is was fixed. I think 8times4's issue is specific to him at this stage. Thanks for the quick fix!
