### ISSUE TITLE
[Bug] If tweet is two or media types, embeds both as images

### ISSUE THREAD

**Issue by GeorgeWL** [dylanpdx/BetterTwitFix#195]
if the tweet is an image with a gif, it embeds both as a composite image, with the first frame of the gif used in the composite 

Example link:  https://fixvx.com/bigbeerfest/status/1760638922084741177?t=sbKUNZ7Qi-ClQXyXLzrjUw&s=19

Which shows as this ![Screenshot_2024-02-22-12-15-30-05_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/dylanpdx/BetterTwitFix/assets/5931248/b64e5161-1cef-4922-88f0-07cf4b3e739c)

**Comment by dylanpdx** [comment]
Fixed in latest refactor
