### ISSUE TITLE
Twitter starting to serve HEVC video files

### ISSUE THREAD

**Issue by Cynosphere** [dylanpdx/BetterTwitFix#197]
Example tweet, found in the wild: https://twitter.com/blephin_/status/1767231724621062406

**Comment by dylanpdx** [comment]
Not sure what I could do about this, Discord doesn't seem to support HEVC (and neither does my browser, for some reason)
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/7f1e7b7b-ad19-41be-987e-72bac36f3597)

**Comment by KingGamingYT** [comment]
Joining in to say how d.vxtwitter.com links will still properly embed videos, but regular links wont't.
![image](https://github.com/dylanpdx/BetterTwitFix/assets/45918062/67a70200-cd89-4fa4-9336-a7e95391e257)

**Comment by dylanpdx** [comment]
I think direct embeds (video only) somehow bypass Discord's internal parsing of them, but embeds with text don't.
Embeds still function normally on other platforms (i.e Telegram) 
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/1b67f650-4151-43ea-8c29-e7c264b3d52e)
I think it's just a matter of Discord lacking support for HEVC. Looks like it was requested a while ago with no response on their end: https://support.discord.com/hc/en-us/community/posts/360032658392-H-265-Video-Codec-Support

**Comment by dylanpdx** [comment]
I've implemented a fix/workaround. Within the next hour or so things should start working again.
Let me know how it goes! If any videos still fail to embed afterwards, send their link here

**Comment by dylanpdx** [comment]
I've verified that the first example link is properly embedding and playing now. Going to wait a while longer to see if any other links with issues pop up, but I think this is solved (for now).
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/c51ddd21-40f2-44f4-8e50-e36bad8307c4)


I don't really like my workaround since I think the alternative non-HEVC videos are lower quality, but for now it'll do.

**Comment by Nama** [comment]
No videos was embeddable before that. Now it works again, thank you!

**Comment by Cynosphere** [comment]
> We love discord and their odd format exclusivity, thanks for the fix.

It's not Discord's fault. If you look at [Can I use](https://caniuse.com/hevc), there are two footnotes for [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=684382) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1332136) respectively that show that neither had interest to implement the codec back in 2017. Chromium has supposedly backpedaled on their stance and supposedly 107 has support for it, but I don't think actual open source Chromium builds, including Electron, do not have the codec due to licensing issues.

Apple is the one shoving HEVC and HE-AACv2 down our throats when no one else (willingly) supports it.

**Comment by Delphox** [comment]
FYI Discord started supporting HEVC videos as of yesterday (?), so if Twitter starts serving HEVC videos again (and also for videos from that timeframe, such as [this one](https://x.com/10431033_65/status/1767230478032216575)) the workaround is no longer necessary.

**Comment by Delphox** [comment]
Oh you're right, I mainly use the web version and they work properly there (and a friend who uses Desktop on Mac also reported them working correctly). So it might be some minor Electron bug on Windows that's causing it, hopefully it's fixed by Discord soon.
