### ISSUE TITLE
[Bug] Embedding of GIFs returns a 0:00 video

### ISSUE THREAD

**Issue by thetrueyoshifan** [dylanpdx/BetterTwitFix#198]
As the title says, embedding a GIF link will result in the GIF being just a single frame and not playing at all. Videos appear to be unaffected by this.
Demo: https://fixvx.com/Scarristo/status/1769368527465525384
![Screenshot 2024-03-18 at 7 09 14 AM](https://github.com/dylanpdx/BetterTwitFix/assets/42860543/62317ae2-9959-4739-8717-cdda27b33597)

**Comment by dylanpdx** [comment]
Seems to be a Discord issue. I've implemented a workaround for now, but I might need to contact them if I want GIF looping to function properly again
