### ISSUE TITLE
[Bug] Video not scrubbing properly

### ISSUE THREAD

**Issue by Ramon20000** [dylanpdx/BetterTwitFix#199]
When you are watching a embedded video it plays correctly unless you try to jump around the video, which causes the video to jump back to the start

Demo: https://vxtwitter.com/FNF_Developers/status/1770547084065706470

https://github.com/dylanpdx/BetterTwitFix/assets/37456831/a0ae2b10-5935-4a21-b8e7-c971c174e4ac

**Comment by dylanpdx** [comment]
This is an issue on Discord's end and not something I can fix.
