### ISSUE TITLE
new twitter feature to be considered

### ISSUE THREAD

**Issue by Nicolas-GE** [dylanpdx/BetterTwitFix#20]
an image and a video can be on the same tweet like this one: https://twitter.com/lilillililXX/status/1578611365513547776

when doing something like `https://fxtwitter.com/lilillililXX/status/1578611365513547776/video/2` , a embedded video is expected
but from my limited testing, the result is either the image in the 1st tab, just the tweet itself, or nothing at all

**Comment by dylanpdx** [comment]
Being worked on in #18
Will keep this open, but I plan on adding as much support for this new feature as I can

**Comment by dylanpdx** [comment]
Fixed in latest
