### ISSUE TITLE
[Request] Direct media links for images

### ISSUE THREAD

**Issue by Overimagine1** [dylanpdx/BetterTwitFix#201]
FxTwitter allows you to [directly post media without the embed](https://github.com/FixTweet/FxTwitter?tab=readme-ov-file#direct-media-links). The only problem with it and the service as a whole is that [the owner is a groomer](https://docs.google.com/document/u/0/d/1SQoVFVx7C_gduAv9Z0SFSF0hke4uK5ZkhFnktPva4zs/), and I do not use services backed by groomers (This isn't a troll, this is genuinely the reason why I don't use it). It would be very nice to see this feature in BetterTwitFix.

**Comment by dylanpdx** [comment]
This is already supported for videos (d.vxtwitter.com) But I will add support for images when I can, hopefully within the next week.

**Comment by Nama** [comment]
The suffixes like `/1`, `/3` etc. aren't working for videos. Only the first video appears.

**Comment by dylanpdx** [comment]
Sorry for the delay, this should be fixed now. Please let me know!

**Comment by Nama** [comment]
Just noticed that my comment was less related to this issue, sorry (but it got implemented now, thank you :D).

Direct images never load. Combined or single image doesn't matter.
https://d.vxtwitter.com/lapis_peak/status/1786348444778647686/2
https://d.vxtwitter.com/lapis_peak/status/1786348444778647686
![image](https://github.com/dylanpdx/BetterTwitFix/assets/2297270/714f8bc6-7171-42f2-97d9-b51481133519)
