### ISSUE TITLE
Some tweets are processed by vxtwitter.com but not by the api + some strange behavior

### ISSUE THREAD

**Issue by Bestulo** [dylanpdx/BetterTwitFix#206]
I was working on a bot today that sent some vxtwitter links, and realized that some links just don't work.

Example: https://x.com/GustavoPetroF/status/1791466911865147664

Going to https://api.vxtwitter.com/Twitter/status/1791466911865147664, I get the html + redirect to the github project (which btw, Postman says it's a status 200 response instead of the 301 or 30X status it would normally be for redirects).

If I send the vxtwitter link (https://vxtwitter.com/GustavoPetroF/status/1791466911865147664), on Telegram the video is correctly set as the thumbnail and it can be viewed and download.

And if I send the aforementioned vxtwitter link on Telegram, it doesn't appear to be the html response I get on browser and postman, but Telegram instead embeds a json file.

This is all very strange and somewhat inconsistent, and it took me some time to figure out. I'd hope the API had some more automation-friendly responses, such as an error code on error, and that if vxtwitter actually has the video, as is shown in the examples, it would show it in the response instead of redirecting to github on error.

I honestly don't know of the source of these problems, and I wish I knew enough python to troubleshoot this but the best I can do right now is post here.

![image](https://github.com/dylanpdx/BetterTwitFix/assets/23301025/2957b640-7f90-4efb-aaff-e5f5975dc957)

**Comment by dylanpdx** [comment]
Sorry for the late reply, I'm currently looking into this

**Comment by Bestulo** [comment]
no problem, I didn't expect you to be on call for this x)

**Comment by dylanpdx** [comment]
This should be fixed now. I'll work on making API errors clearer in the future, but for now tweets that exist should load properly. Feel free to re-open if you encounter any other issues!
