### ISSUE TITLE
vxtwitter.com link previews are not previewing

### ISSUE THREAD

**Issue by rarDevelopment** [dylanpdx/BetterTwitFix#207]
It looks like vxtwitter.com previews are no longer working. Could this be related to the [domain change](https://x.com/elonmusk/status/1791351500217754008) to x.com across the board?

![image](https://github.com/dylanpdx/BetterTwitFix/assets/4060573/5055ea69-de41-4ec4-a515-6c7b0d022864)

**Comment by dylanpdx** [comment]
Just pushed some changes that should slowly fix this. Twitter seems to have changed their rate limits along with the domain change

**Comment by dylanpdx** [comment]
This should be fixed now. Feel free to re-open if you encounter any other issues!
