### ISSUE TITLE
2024/05/18: NSFW Tweets failing to embed

### ISSUE THREAD

**Issue by dylanpdx** [dylanpdx/BetterTwitFix#208]
Lots of changes over at Twitter recently, main issue at the moment is that rate limits are being triggered even though the `x-rate-limit-remaining` header says it shouldn't be.

**Comment by Nama** [comment]
It still works on fxtwitter btw. Maybe its related to your account or something.

**Comment by dylanpdx** [comment]
Issue seems to be fixed by using a different bearer token. Will close later if it continues to work

**Comment by Nama** [comment]
Happening again on NSFW tweets

**Comment by dylanpdx** [comment]
Hopefully fixed.. again, in https://github.com/dylanpdx/BetterTwitFix/commit/ceb27fa82e25806ce3b72b7cb07a5eb5729cccd9
