### ISSUE TITLE
Can't make request to api.vxtwitter.com using JavaScript's fetch function

### ISSUE THREAD

**Issue by pinkie-pie0** [dylanpdx/BetterTwitFix#209]
If I attempt to use the fetch function then I get `Cross-Origin Request Blocked` as the error message, seemingly due to the fact I'm making the request from a different domain. Is this intended to be a self-host-only feature instead?

**Comment by Nama** [comment]
I think it should just work if you set the header `Access-Control-Allow-Origin: *` on your own webserver.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by dylanpdx** [comment]
Please check now, CORS should be set up correctly now

**Comment by pinkie-pie0** [comment]
> Please check now, CORS should be set up correctly now

Still fails, but now I'm getting `Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, *’` instead.
