### ISSUE TITLE
Majority of videos broken on iOS

### ISSUE THREAD

**Issue by KingGamingYT** [dylanpdx/BetterTwitFix#210]
Surprised to see no issue about this. For a few months now videos in embeds SPECIFICALLY on Apple devices will sit on 0:00/0:00 infinitely, with very few exceptions. Could this be due to the previous HEVC video serving Twitter began to do?

**Comment by KingGamingYT** [comment]
https://github.com/dylanpdx/BetterTwitFix/assets/45918062/37430058-cec5-455e-bd03-cb553b161a76

Video showcasing the issue.

**Comment by dylanpdx** [comment]
That tweet you linked to specifically uses AVC1 so it doesn't seem to be a HEVC related issue
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/df459cb7-0579-4bc6-aefb-c3f280cb913c)
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/e4feb5ea-ffae-4c94-8914-8b8dd5771571)

Not quite sure what could be causing this case, but I do know Discord embeds on iOS have several issues (not including this one)

**Comment by dylanpdx** [comment]
I think I narrowed down the issue. It'll be a hacky fix most likely

**Comment by dylanpdx** [comment]
Can you check if it's fixed now? Old embeds will still have the problem unfortunately but I'm seeing new ones start to work.
I was originally going to do a much more complicated fix but I think I found a simpler way, hopefully

**Comment by KingGamingYT** [comment]
> Can you check if it's fixed now? Old embeds will still have the problem unfortunately but I'm seeing new ones start to work. I was originally going to do a much more complicated fix but I think I found a simpler way, hopefully

Seems to work! Tested with the same post (re-sent) and a new one as well.

**Comment by KingGamingYT** [comment]
Update: It looks like it's still broken, but maybe only on quote tweets? Here's an example: https://vxtwitter.com/Not_Prasar/status/1795007948839698882?s=19
![image](https://github.com/dylanpdx/BetterTwitFix/assets/45918062/3e2517af-aec3-4c36-9ed0-4a2d7f4da1a3)

**Comment by etriebe** [comment]
@dylanpdx still broken for any embed on iOS for me. Any ideas?

**Comment by dylanpdx** [comment]
@etriebe 
> @dylanpdx still broken for any embed on iOS for me. Any ideas?

I can't replicate this on iOS, both videos linked above seem to be playing for me. Do you have a specific twitter link I can look at?
Also worth noting that Discord has been making quite a few bugfixes on their iOS app recently so it might just be a matter of checking if you're on the latest version. My app version says 238.0

**Comment by etriebe** [comment]
This was the one I was testing with.

https://x.com/DiscussingFilm/status/1813952065636638931

—Eric Triebe
________________________________

**Comment by dylanpdx** [comment]
I have a fix for this coming soon

**Comment by dylanpdx** [comment]
This should be hopefully fixed now. Please let me know if there's any Tweets that still don't play

**Comment by etriebe** [comment]
Fixed! Brilliant! Thank you!

—Eric Triebe
________________________________
