### ISSUE TITLE
Text length is shorter since few weeks

### ISSUE THREAD

**Issue by Nama** [dylanpdx/BetterTwitFix#214]
Text seems to be cut of at 209 characters it seems. That is the case since a few weeks I think.
fxtwitters embeds don't cut off at 210.

https://vxtwitter.com/sillintor/status/1802807577379528803

The last commit I could find extended the length to 340? But without manual cutting and let discord auto-cut it?
Thats weird...

Thank you for keeping this alive!

**Comment by dylanpdx** [comment]
Unfortunately Discord sometimes decides to not render the embed if it goes past the text limit.
The issue is valid though, Text embeds have a length of 340, and Video embeds have the lower limit. This should be fixed now

**Comment by Nama** [comment]
But this is not a video and is cut off at 209:
https://vxtwitter.com/sillintor/status/1802807577379528803

**Comment by dylanpdx** [comment]
Embeds take a while to refresh on Discord's end. It's supposed to be 30 minutes but sometimes it takes longer.
On mine it's already visible, so it might be per channel too? I'm not sure how this is cached on Discord's end
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/f229c203-f67e-400c-9017-2f23a9a5704d)

**Comment by Nama** [comment]
lol yeah, seems like it. Thought after 2 hours it would load it again.
Sorry and thank you!
