### ISSUE TITLE
Trans Flag not rendering properly; displays as 🏳️‍ instead of either the flag proper or the 🏳️‍⚧️ emojis.

### ISSUE THREAD

**Issue by GenesisEra** [dylanpdx/BetterTwitFix#215]
Noticed an issue with vxtwitter where original tweets with the trans flag in them are rendered in vxtwitter embeds as just a white flag (🏳️‍). Examples below (username cropped for propriety):

Original Twitter Image (shows trans flag):
![image](https://github.com/dylanpdx/BetterTwitFix/assets/173928551/c88f368b-f44c-46d0-b61c-dbea003b4480)

Twitter/X Embed on Discord (shows trans flag):
![image](https://github.com/dylanpdx/BetterTwitFix/assets/173928551/bfda754f-eb7f-43e5-83e7-2ad6a2a6792d)

VxTwitter Embed on Discord (The One With the White Flag Error):
![image](https://github.com/dylanpdx/BetterTwitFix/assets/173928551/815e5aee-bb41-49ec-82fc-ff9583d9d3b0)

I looked it up, and it looks like VxTwitter is only rendering the first half of the characters for the transgender emoji (🏳️‍⚧️) that converts into the flag?

Does anyone know how to fix this in the code?

**Comment by dylanpdx** [comment]
This is probably an issue with your device, as the same tweet renders correctly for me on Discord desktop/mobile.
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/1269ca53-fcce-40e4-b706-2f645cfb45aa)
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/ce53abf0-9997-4582-8df5-3906ea9f9cca)

I'm not sure what could be causing this though, besides maybe an emoji font that doesn't have the trans flag in it.
You're correct in that there's two characters required to render the flag, but they both are visible in your screenshot (🏳️ and ⚧️) so I think it's something on the device that isn't combining them
