### ISSUE TITLE
fixvx redirects to vxtwitter?

### ISSUE THREAD

**Issue by MonfGeiger** [dylanpdx/BetterTwitFix#225]
i've been mainly using fixvx since all twitter links have long since switched to x.com links, yet lately, when i click on a fixvx link, it redirects to vxtwitter, and since i have auto-redirect on my firefox browser adjusted, this happens
![Capture](https://github.com/user-attachments/assets/289d4d23-777f-4640-a38f-29967a87fc0c)
was this intentional, or no?

also, that auto-redirect adjustment thing with my web browser for websites (separate from twitter) was intentional, and i will not be changing it back because of certain reasons i will not disclose

**Comment by dylanpdx** [comment]
This was probably a result of a change I made yesterday. I'll hopefully have a fix for this out within the day. Sorry for the inconvenience!

**Comment by MonfGeiger** [comment]
so the fixvx no longer redirects to vxtwitter, but the above pic thing still happens, even when back then it didnt

**Comment by dylanpdx** [comment]
Not much I can do then, a recent FF update might have changed things, because the site was always redirecting to Twitter once the link was clicked, even if fixvx/vxtwitter was used

**Comment by deusexcalamus** [comment]
The white screen for 'redirecting you to the video in a moment....' is kinda eye-searing when you're generally using dark themes, is that possible to fix? ALso, I find it funny that it says 'redirecting you to the video' when there's no video in the tweet.

**Comment by Nama** [comment]
### Disabled
Firefox asks to open the app and doesn't load the twitter website

### Enabled
Firefox asks to open the app *and* loads the twitter site

just fyi^^ I'll keep it disabled.
oh, only tested with vxtwitter, not fixvx.

**Comment by dylanpdx** [comment]
> The white screen for 'redirecting you to the video in a moment....' is kinda eye-searing when you're generally using dark themes, is that possible to fix? Also, I find it funny that it says 'redirecting you to the video' when there's no video in the tweet.
> 
> Edit: This is clicking on vxtwitter links from desktop discord/desktop firefox.

I'll take a look at this later today



> ### Disabled
> 
> Firefox asks to open the app and doesn't load the twitter website
> ### Enabled
> 
> Firefox asks to open the app _and_ loads the twitter site
> 
> just fyi^^ I'll keep it disabled. oh, only tested with vxtwitter, not fixvx.

What setting in Firefox are you enabling/disabling?

**Comment by Nama** [comment]
> What setting in Firefox are you enabling/disabling?

nothing, i mean the new option you added https://vxtwitter.com/preferences

**Comment by deusexcalamus** [comment]
> > The white screen for 'redirecting you to the video in a moment....' is kinda eye-searing when you're generally using dark themes, is that possible to fix? Also, I find it funny that it says 'redirecting you to the video' when there's no video in the tweet.
> > Edit: This is clicking on vxtwitter links from desktop discord/desktop firefox.
> 
> I'll take a look at this later today
> 
> > ### Disabled
> > Firefox asks to open the app and doesn't load the twitter website
> > ### Enabled
> > Firefox asks to open the app _and_ loads the twitter site
> > just fyi^^ I'll keep it disabled. oh, only tested with vxtwitter, not fixvx.
> 
> What setting in Firefox are you enabling/disabling?

As a note it doesn't do it on fixupx.com links, just vxtwitter

**Comment by dylanpdx** [comment]
> > What setting in Firefox are you enabling/disabling?
> 
> nothing, i mean the new option you added https://vxtwitter.com/preferences

That's unrelated to this issue, please post this in #216

**Comment by IcicleAI** [comment]
why is there a redirect in the first place? fxtwitter, and vxtwitter, and fixvx (till a few days ago) worked perfectly fine without the redirect, and fx still does.

**Comment by dylanpdx** [comment]
The redirect isn't new, otherwise moving you from the vx domain to twitter.com wouldn't happen. 
What changed was the method used to perform redirect, which was to add support for opening tweets in the mobile app.

**Comment by IcicleAI** [comment]
ah. just annoying to have the extra page show up when it never really has before
