### ISSUE TITLE
bug on like/RT counter

### ISSUE THREAD

**Issue by x0rld** [dylanpdx/BetterTwitFix#34]
https://twitter.com/elonmusk/status/1586104694421659648
it has hit 2 millions 💖 and 228.6K Retweets 34.7K Quote Tweets and it said 💖 4713 🔁 592

https://twitter.com/elonmusk/status/1580350143445942272
the second one is not that much different
display: 💖 306060 🔁 19826
twitter:  19.8K Retweets 1,975 Quote Tweets 306K 💖

**Comment by dylanpdx** [comment]
When a post is ran through VX, I usually save a local copy of it just so I don't have to keep coming back to Twitter over and over. It usually sticks around for a day before refreshing, so it might take that long for likes to be accurate. I'm considering lowering this to 12 hours or even 1 hour, but at the moment It's set to 1 day

**Comment by x0rld** [comment]
oh ok thx for the reply
