### ISSUE TITLE
animation loops request

### ISSUE THREAD

**Issue by unlightednetting** [dylanpdx/BetterTwitFix#35]
Hello, I'm not sure how hard this would be, the literal only "complaint" that I have for this site/code is that the kind of animations that I often see are about 1 to 6 seconds, and I would love to see an option to have them continually loop. Seems like a potential addition to links ending in mp4

Here is a wonderful example: https://twitter.com/Kekeflipnote/status/1584464315662602240

**Comment by dylanpdx** [comment]
Will work on this 👍

**Comment by dylanpdx** [comment]
Tweets with GIFs should now loop(ish), ish because they're repeated until they are 30 seconds long.
I wanted to convert them to raw GIF but the file sizes are just too big to make the experience fast for users. Maybe in the future
