### ISSUE TITLE
vxtwitter links not redirecting to twitter links ("Bad Gateway")

### ISSUE THREAD

**Issue by whizzball1** [dylanpdx/BetterTwitFix#4]
Hello!

When I use vxtwitter links on Discord, the embed works great, but when I click the link, I'm no longer directed to the actual Twitter page. I get the error message "502 Bad Gateway".

I think this is a very recent issue! It wasn't like this before, so perhaps something broke down the pipeline.

**Comment by whizzball1** [comment]
As of the time I'm writing this comment, this is no longer an issue. I'm not going to close it just yet, though, in case it alerts the devs of some occasional issue that needs fixing.

**Comment by dylanpdx** [comment]
This has been fixed internally so i'm closing this for now
