### ISSUE TITLE
Include Link to Account in Embed

### ISSUE THREAD

**Issue by AbbyAbbyAbbyAbby** [dylanpdx/BetterTwitFix#43]
While a niche use case, I use a browser plugin that highlights links of tweets and accounts that I have added to archival programs. The default twitter embed includes a link to the account page, so that link is detected and highlighted by the plugin. However the vxtwitter embed has a link to the post, which isn't always highlighted as the archival programs don't frequently check for new posts (every few days/weeks).

I see this as a bit redundant, as the same post link is directly above the embed. I think it could just be changed to the account link, or if supported by web embeds the `author url` parameter for discord could be used so the `vxTwitter` would link to the account. Either way would make the link highlighting work for this program and let users see if they have an account archived at a glance.

This is said plugin for reference, sorry for no screenshots. It integrates with the later two links. No support is directly needed for these, just changing the link to point to the account page will work. I included these to show that while niche, there's still an amount of people that could benefit from this change.
<https://gitgud.io/prkc/hydrus-companion>
<https://gitgud.io/thatfuckingbird/hydownloader>
<https://github.com/hydrusnetwork/hydrus>

**Comment by dylanpdx** [comment]
Sorry for the extremely late reply on this.
It should be happening now for embeds, if you could confirm it works with Hydrus that'd be great!

**Comment by AbbyAbbyAbbyAbby** [comment]
Yep, works fine now, thank you very much!
