### ISSUE TITLE
Tweet text as well as video in telegram?

### ISSUE THREAD

**Issue by Deer-Spangle** [dylanpdx/BetterTwitFix#6]
Hey there
When using a vxtwitter link in telegram, it just shows the video, but not the text. Is it possible for it to show both the video and the text, or is this a limitation on telegram's side?
At the moment, I see a lot of folks posting a twitter link and a vxtwitter link, or posting the vxtwitter link and copy-pasting the caption into the message or whatnot.
An example:
![image](https://user-images.githubusercontent.com/60626596/172029928-22556cd6-b0c5-4c28-b55b-1e56c864c4a1.png)

**Comment by dylanpdx** [comment]
Hey! 
From what I remember, there's some limitations on what fields embeds can have, but it's more of a Discord thing and it shouldn't apply to Telegram.

I'll look into this tomorrow and hopefully get back to you then if I figure it out

**Comment by dylanpdx** [comment]
Just fixed this in https://github.com/dylanpdx/BetterTwitFix/commit/e28789a09dbb6efd36827a3fd47e0132666a9609
Tweet content should now display properly on videos embedded within Telegram.
![image](https://user-images.githubusercontent.com/1337360/172051064-731d14d0-c129-450a-9a6a-e8b753b9ef4d.png)
