### ISSUE TITLE
Extend description length

### ISSUE THREAD

**Issue by MrBoombastic** [dylanpdx/BetterTwitFix#61]
It appears that the embed description is trimmed to about 240 characters. It would be nice if this limit could be increased, maybe to 500 characters?

**Comment by dylanpdx** [comment]
This isn't possible, as Discord embeds are limited in size, which means there's nothing I could do unless Discord themselves change it

**Comment by MrBoombastic** [comment]
I mean, Discord embed description is limited to [2048 characters](https://discord.com/moderation/4405223159703-322-using-webhooks-and-embeds). Look, default Twitter embed is in this case showing all the content.
![image](https://user-images.githubusercontent.com/18630357/219726796-32fb8463-7f54-4d49-837f-57ced40e0d53.png)
![image](https://user-images.githubusercontent.com/18630357/219726975-2bd09d6d-e7d0-42d5-9d35-67cc63781ae7.png)

**Comment by dylanpdx** [comment]
The 2048 character limitation applies to webhooks and bots, and the twitter embed also gets special treatment (in the same way youtube, twitch, etc. get special embeds) and can bypass these restrictions.

However, I just checked on a test instance and it seems Discord increased the limit of non-special embeds from 240 characters to 340. I'll add support for that in a bit.

Keep in mind anything above 340 will still be cut off, as Discord adds it's own "..." ending. This test had 1024 A's 
![image](https://user-images.githubusercontent.com/1337360/219734657-0fdae9c4-15af-46ec-a174-2352fee3196f.png)

**Comment by MrBoombastic** [comment]
Okay, so embeds are even more confusing than I thought they are. Thank you for raising the limit!
