### ISSUE TITLE
(Android) Video downloads as a .bin

### ISSUE THREAD

**Issue by SqueakyFox** [dylanpdx/BetterTwitFix#77]
I just moved to android and so I know the issue is non existent on IOS but for some reason whenever I download a video it downloads as a .bin and I need to go into a file editor and manually change the extension to .mp4 to fix it, I dunno if there's any fix for it..

**Comment by dylanpdx** [comment]
I was able to replicate this on my phone but I think this is an issue more on Discord's end.
