### ISSUE TITLE
Other VX Services

### ISSUE THREAD

**Issue by MisterCookie1234** [dylanpdx/BetterTwitFix#9]
Hello. I know this is the wrong place to ask but i couldn't figure out where to ask. 
I saw you expanded the VX Service to TikTok and i was wondering if u planned to do it for 9GAG or Reddit aswell? 

Greetings

**Comment by dylanpdx** [comment]
I do have a VX Reddit planned, but not sure about a vx9gag, since I don't know the issues with their embeds.
Mind sending an example 9GAG link that doesn't embed properly on discord?

**Comment by MisterCookie1234** [comment]
Here: https://9gag.com/gag/aNPXB3K

In Discord it just looks like this.
![image](https://user-images.githubusercontent.com/24813669/175544035-a145c853-2b72-498b-a0fa-260d5e23d960.png)

Can't be clicked or whatever.

**Comment by dylanpdx** [comment]
I probably won't be supporting 9gag, but as mentioned Reddit is planned
