### ISSUE TITLE
Changes to Twitter API has broken Tweet with video embeds in Discord

### ISSUE THREAD

**Issue by Toxici-Ty** [dylanpdx/BetterTwitFix#91]
When linking a Tweet containing a video the tweet and text embeds but the video is not present.  This is likely due to recent changes in the Twitter API as I know some video download sites also broke recently after these changes.

**Comment by dylanpdx** [comment]
I'm not able to replicate this, example tweets I tested:
https://vxtwitter.com/NintendoAmerica/status/1657846000135077893
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/8bc33c6c-d596-4e53-8029-2c0ca3a264ff)

https://vxtwitter.com/Twitter/status/1263145271946551300
![image](https://github.com/dylanpdx/BetterTwitFix/assets/1337360/8973a477-3082-4a79-bf0f-0c2eec4c34c4)

**Comment by Toxici-Ty** [comment]
Yeah now I've looked deeper than the couple of tweets I was working with initially it seems hit or miss.  I'm wondering if it's only tweets flagged as sensitive as it was an uhm... naughty Discord that I first noticed the issue.

**Comment by Toxici-Ty** [comment]
That's not it either.  I've found a couple videos that embed properly that are marked as potentially sensitive content.  

Unless there's a difference between content that is flagged sensitive later and that flagged sensitive by the uploader.

**Comment by dylanpdx** [comment]
Yeah, I've just tried some flagged tweets which worked fine on my end as well

**Comment by Toxici-Ty** [comment]
My next level of inquiry was account specific maybe something flagged on the back end but there are also videos from the same account that both work and don't work.   Seems impossible to accurately replicate. as it's just random.  

It seems all the tweets that don't work are flagged sensitive, but not all sensitive tweets don't work.

**Comment by Toxici-Ty** [comment]
I think I've found what's the difference between those that work and those that don't. 

Any video that has the From [Account name here] does not embed, but it seems ONLY when the original tweet is marked as sensitive?  Weird.  Any tweet that uploaded the video directly is working.  Tweets not marked sensitive with the From [Account Name] work.

**Comment by dylanpdx** [comment]
Some example tweets that work and don't work would be great to have if you can find any, so far everything I've tested seems to go through fine. I wonder if this specific user is shadowbanned, but I don't see how it would affect individual tweets..

**Comment by Toxici-Ty** [comment]
I mean I didn't just want to post a bunch of dirty Tweets for you to look at and subject you to.  Though my reply above seems to be what's going on.  

I even found an example of an account where they retweeted their own videos with the method above and the original tweet embeds and the new tweet with the From [Account name] doesn't.

**Comment by dylanpdx** [comment]
It might also be Discord itself having issues with embeds, it's rare but it happens. Don't know of anything else that could be causing issues tbh unless it's some as of yet unknown API limitation

**Comment by Toxici-Ty** [comment]
Yeah, as a temporary workaround any Tweet I've encountered that doesn't work if you click on the name in the From [Account Name] below the video and link the ORIGINAL tweet it will embed properly every time. 

Sorry to bother you.

**Comment by Nama** [comment]
This one doesnt work. its a QRT of a video.
https://twitter.com/Mlickles/status/1658191524818223104

**Comment by dylanpdx** [comment]
Tracked down the issue with this video, thanks! I'll fix it shortly

**Comment by dylanpdx** [comment]
Issue has been fixed and the update is rolling out now. Some services like Discord might take a while for

**Comment by Nicolas-GE** [comment]
might be related, https://twitter.com/NoContextHumans/status/1663539613611466755 does not embed correctly
my best guess is that it's the "from `account`" that is breaking it
