### ISSUE TITLE
Cannot open http link

### ISSUE THREAD

**Issue by kumikooumae** [dylanpdx/BetterTwitFix#97]
I can't open the http://vxtwitter.com/... link. It will give ERR_EMPTY_RESPONSE, and I need to manually change it to https to open the page. Tested on iOS Safari and Android Chrome. PC and Android Firefox can automatically jump to https and open the link however.

**Comment by dylanpdx** [comment]
HTTP isn't supported by my hosting solution and honestly it's not a huge issue for me since all twitter links are https
